/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'README',
    'architecture',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['examples', 'low-cost-dev-clusters', 'autopilot-clusters'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['runbook', 'cicd-azure-oidc'],
    },
    {
      type: 'category',
      label: 'CLI reference',
      items: [{type: 'autogenerated', dirName: 'cli'}],
    },
    {
      type: 'category',
      label: 'Code reference',
      items: [
        'reference/index',
        'code-organization',
        'reference/core',
        'reference/auth',
        'reference/kubeconfig',
        'reference/provisioner-aws',
        'reference/provisioner-gcp',
        'reference/provisioner-azure',
        'reference/provisioners',
        'reference/repo',
        'reference/registry',
        'reference/catalog',
        'reference/argocd',
        'reference/orchestrator',
        'reference/cli',
        'reference/entrypoints',
      ],
    },
    'development',
  ],
};

export default sidebars;
